application: filenotary
version: 1
runtime: go
api_version: go1

handlers:

- url: /style\.css
  static_files: style.css
  upload: style\.css

- url: /admin/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
